### PR TITLE
Add ChefSpec matchers

### PR DESCRIPTION
**Pull request by szymonpk**
Now, it's possible to test all resources interactions using ChefSpec.

### CODE REVIEW

**Comment by flaccid** [comment]
Possible to address https://travis-ci.org/xhost-cookbooks/system/jobs/124701545 first?

**Comment by szymonpk** [comment]
Action is `set` so with ChefSpec best practices I've seen so far it should be `set_system_hostname` and `set_system_timezone`. I'll disable this check in matchers.rb file.

**Comment by flaccid** [comment]
You will probably still need to make an exception with rubocop to pass.

**Comment by szymonpk** [comment]
Ok, it's passing all checks now.

**Comment by flaccid** [comment]
Thanks !

**Pull request merged**
