### PR TITLE
Configure /etc/profile

### PR DESCRIPTION
**Pull request by brauliobo**
A new recipe and LWRP to configure `/etc/profile`

### CODE REVIEW

**Comment by flaccid** [comment]
Before code review please ensure the build passes. One other thought is whether or not it's a good idea to template all of `/etc/profile`.

**Comment by brauliobo** [comment]
build is passing now.

I've studied and compared `/etc/profile` from archlinux and ubuntu, and primarily based on ubuntu.

I would add and document this feature as experimental

**Comment by flaccid** [comment]
Thanks @brauliobo appreciate your contribution. I'll have a play with this and start documenting it too. Its likely that we'll end up having a separate template for each platform. Will have this come out in next release.

**Comment by brauliobo** [comment]
@flaccid you're welcome :)

**Pull request merged**
