### PR TITLE
Use ohai to determine network IP, allow specification primary network interface for hostsfile generation.

### PR DESCRIPTION
**Pull request by jhohertz**
- adds a primary_interface config value, defaulting to what Ohai found to be the default_interface.
- hostfile entry for the local node switched to use ohai network info, using the primary_interface as a key. The first IP address found on the interface is used, matching prior behaviour.
- Useful for test kitchens, allowing the vagrant NAT interface to be side-stepped for the purposes of generating /etc/hosts (IE: trying to simulate clusters, which were getting bad reverse lookup info via the existing behaviour for generation of /etc/hosts

Thought this would be useful to others, and I'm happy to adjust the code to get it upstream.

Thanks for having a look.

### CODE REVIEW

**Comment by flaccid** [comment]
Thanks very much for this. Could we just get the tests to pass and see if we can write a few tests for this functionality?

**Comment by jhohertz** [comment]
Having a look into that now.

**Comment by jhohertz** [comment]
Re: testing the functionality, I'll need to add a private interface to the kitchen suite.

Any suggestions on what IP/network would be best to use?

**Comment by flaccid** [comment]
@jhohertz there are known range conflicts that is true. I ended using https://github.com/flaccid/rancher-test-farm/blob/master/Vagrantfile#L13-L14 - anything in that /16 should be ok iirc.

**Comment by flaccid** [comment]
@jhohertz any luck? I've been starved for time lately, don't mind waiting for those tests before we release next.

**Comment by jhohertz** [comment]
Yeah I know the feeling.... I fixed the style warnings but need to add a test still, i'll try to look at that today.

**Comment by jhohertz** [comment]
So at this point I have added a test which ensure coverage of the new feature, but not sure how I can test not using it without launching a second suite without the feature enabled. If you'd like me to go that route, I'll happily set it up, but it feels a bit extreme for one test.

Let me know, otherwise I think it's good to go. Happy to hear other suggestions on approach.

**Comment by flaccid** [comment]
I'll ponder on that notion, its always a hard one to test different integration setups. Thanks very much for this!

**Pull request merged**
